# Generated by Django 4.2.20 on 2025-06-02 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('country', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('ssn', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField()),
                ('picture_url', models.TextField(blank=True, null=True)),
                ('related_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passengers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='bookings.location')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='bookings.location')),
            ],
            options={
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('remaining_sections', models.PositiveSmallIntegerField()),
                ('remaining_capacity', models.PositiveSmallIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bookings.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='companies.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_seats', models.PositiveSmallIntegerField(default=0)),
                ('seat_start_number', models.PositiveSmallIntegerField(default=0)),
                ('seat_end_number', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='companies.vehiclesection')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.trip')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes_destination', to='bookings.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='bookings.location'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes_origin', to='bookings.station'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('reservation_date', models.DateField(auto_now_add=True)),
                ('reservation_time', models.TimeField(auto_now_add=True)),
                ('expiration', models.DurationField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reservations', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.passenger')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bookings.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'Paypal'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Wallet', 'Wallet')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=10)),
                ('payment_time', models.TimeField(auto_now_add=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveSmallIntegerField()),
                ('stop_type', models.CharField(choices=[('Transit', 'Transit'), ('Meal', 'Meal'), ('Refuel', 'Refuel'), ('Layover', 'Layover')], max_length=10)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.station')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bookings.trip')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('trip', 'stop_order')},
            },
        ),
    ]
