# Generated by Django 5.2.1 on 2025-06-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='ssn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
