# Generated by Django 4.2.20 on 2025-06-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='remaining_capacity',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='remaining_sections',
        ),
    ]
