# Generated by Django 4.2.20 on 2025-06-08 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_trip_remaining_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='expiration',
        ),
    ]
