# Generated by Django 4.2.20 on 2025-06-08 19:41

import bookings.models.reservation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_reservation_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='expiration_time',
            field=models.DateTimeField(default=bookings.models.reservation.default_expiration_time),
        ),
    ]
