# Generated by Django 5.2 on 2025-05-30 03:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin'), ('Company_Owner', 'Company Owner')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Banned', 'Banned')], default='Active', max_length=20)),
                ('password_hash', models.TextField()),
                ('city_id', models.BigIntegerField(blank=True, null=True)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.account')),
            ],
            options={
                'db_table': 'wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('related_payment_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('Charge', 'Charge'), ('Payment', 'Payment'), ('Refund', 'Refund')], max_length=10)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_time', models.TimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.wallet')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
    ]
