# Generated by Django 5.2 on 2025-05-30 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='city_id',
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.location'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='related_payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.payment', unique=True),
        ),
    ]
