# Generated by Django 5.2 on 2025-05-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_city_id_account_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='city',
            new_name='city_id',
        ),
    ]
