# Generated by Django 5.2 on 2025-05-30 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_city_account_city_id'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='related_payment_id',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='related_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.payment'),
        ),
    ]
