# Generated by Django 5.2 on 2025-05-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_wallettransaction_related_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='related_payment',
            new_name='related_payment_id',
        ),
    ]
