# Generated by Django 5.2 on 2025-05-30 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_related_payment_wallettransaction_related_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='city_id',
            new_name='city',
        ),
    ]
