# Generated by Django 5.2 on 2025-06-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_birthdate_account_birth_date_account_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin'), ('Company_Admin', 'Company Admin')], max_length=20),
        ),
    ]
